# Generated by Django 5.0.3 on 2024-03-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triggers_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='environment',
            field=models.CharField(choices=[('global', 'global'), ('environment-specific', 'environment-specific'), ('application-specific', 'application-specific')], default='global', max_length=100),
        ),
    ]
