# Generated by Django 5.0.3 on 2024-03-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triggers_app', '0002_trigger_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='meta_data',
            field=models.JSONField(null=True),
        ),
    ]
